name: nfc_deck_tracker
description: "A Flutter app for managing and tracking card decks using NFC technology."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase & Authentication
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.6
  google_sign_in: ^6.2.2

  # Storage & Local Database
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1

  # State Management & DI
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2

  # Utilities & Helpers
  connectivity_plus: ^6.1.3
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  nfc_manager: ^3.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.0+1
  uuid: ^4.5.1

  # UI & Visual
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  fl_chart: ^0.70.2
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/image/
    - assets/image/game/
    - assets/locale/
